services:
  - type: web
    name: bet-arena-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: bet-arena-backend
          envVarKey: PORT 